module.exports = {
  USER_SORT_ARRAY: [
    'firstname-desc',
    'firstname-asc',
    'lastname-desc',
    'lastname-asc',
    'createdAt-desc',
    'createdAt-asc',
    'updatedAt-desc',
    'updatedAt-asc',
  ],
  QUESTION_SORT_ARRAY: [
    'UserId-desc',
    'UserId-asc',
    'CategoryId-desc',
    'CategoryId-asc',
    'totalAnswers-desc',
    'totalAnswers-asc',
    'hasAcceptedAnswer-desc',
    'hasAcceptedAnswer-asc',
    'createdAt-desc',
    'createdAt-asc',
    'updatedAt-desc',
    'updatedAt-asc',
  ],
  ANSWER_SORT_ARRAY: [
    'UserId-desc',
    'UserId-asc',
    'upVotes-desc',
    'upVotes-asc',
    'downVotes-desc',
    'downVotes-asc',
    'isAcceptedAnswer-desc',
    'isAcceptedAnswer-asc',
    'totalComments-desc',
    'totalComments-asc',
    'createdAt-desc',
    'createdAt-asc',
    'updatedAt-desc',
    'updatedAt-asc',
  ],
  COMMENT_SORT_ARRAY: [
    'UserId-desc',
    'UserId-asc',
    'createdAt-desc',
    'createdAt-asc',
    'updatedAt-desc',
    'updatedAt-asc',
  ],
};
